version: '3'
services:
  app:
    container_name: notify_sync_server_container
    hostname: notify_sync_server_container
    image: krlsedu/notify-sync-server
    restart: always
    ports:
      - "8088:8890"
    networks:
      - notify_sync_server_network
networks:
  notify_sync_server_network:
